local defaults = require("lib.tuning_defaults").values

data:extend({
   {
      type = "double-setting",
      name = "sloptorio-base-effect-quality",
      setting_type = "startup",
      default_value = defaults.base_effect_quality,
      minimum_value = -100,
      maximum_value = 100,
      order = "a",
   },
   {
      type = "double-setting",
      name = "sloptorio-normal-next-probability",
      setting_type = "startup",
      default_value = defaults.normal_next_probability,
      minimum_value = 0,
      maximum_value = 1,
      order = "b",
   },
   {
      type = "double-setting",
      name = "sloptorio-fine-next-probability",
      setting_type = "startup",
      default_value = defaults.fine_next_probability,
      minimum_value = 0,
      maximum_value = 1,
      order = "c",
   },
   {
      type = "double-setting",
      name = "sloptorio-uncommon-next-probability",
      setting_type = "startup",
      default_value = defaults.uncommon_next_probability,
      minimum_value = 0,
      maximum_value = 1,
      order = "d",
   },
   {
      type = "double-setting",
      name = "sloptorio-rare-next-probability",
      setting_type = "startup",
      default_value = defaults.rare_next_probability,
      minimum_value = 0,
      maximum_value = 1,
      order = "e",
   },
   {
      type = "double-setting",
      name = "sloptorio-epic-next-probability",
      setting_type = "startup",
      default_value = defaults.epic_next_probability,
      minimum_value = 0,
      maximum_value = 1,
      order = "f",
   },
   {
      type = "double-setting",
      name = "sloptorio-module-quality-scale",
      setting_type = "startup",
      default_value = defaults.module_quality_scale,
      minimum_value = 0,
      maximum_value = 100,
      order = "g",
   },
   {
      type = "double-setting",
      name = "sloptorio-module-quality-base-step",
      setting_type = "startup",
      default_value = defaults.module_quality_base_step,
      minimum_value = 0.000001,
      maximum_value = 10,
      order = "h",
   },
   {
      type = "double-setting",
      name = "sloptorio-module-quality-exponent",
      setting_type = "startup",
      default_value = defaults.module_quality_exponent,
      minimum_value = 0,
      maximum_value = 10,
      order = "i",
   },
   {
      type = "double-setting",
      name = "sloptorio-module-quality-per-level-bonus",
      setting_type = "startup",
      default_value = defaults.module_quality_per_level_bonus,
      minimum_value = 0,
      maximum_value = 10,
      order = "j",
   },
})
